// TAHMİN SİCİLİ — veri seti v1 (9 Temmuz 2026)
// Kaynak: 51 DK-dönemi yayınının transkript çıkarımı (859 tahmin tespit edildi;
// yalnız bağlam kanıtıyla kişiye atananlar yayınlanır). Hükümler, yayınlarda
// söylenen sonuçlara dayanır; her kayıtta kaynak yayın linki vardır.
const SICIL = {
  guncelleme: "20 Temmuz 2026 — SİCİL KAPANDI",
  kapsam: { yayin: 60, tahmin: 859, atanmis: 127, yuzlesme: 101 },

  karne: [
    {
      kisi: "Hilmi",
      unvan: "Kanalın Kâhini",
      grupPuan: "28+", grupSira: 1,
      sampiyon: { pick: "İspanya → Arjantin → İspanya", durum: "TUTTU",
        not: "10 Haziran'da İspanya dedi, 28 Haziran'da Arjantin'e döndü, 15 Temmuz'da İspanya'ya geri döndü — ve İspanya kupayı kaldırdı (19 Tem, 1-0). Üç dönüşün sonunda hem başladığı hem bitirdiği tahmin şampiyon oldu; üstüne kanalın kendi tahmin oyununu da ikinci kez şampiyon bitirdi." },
      tally: { tuttu: 3, kismen: 3, coktu: 4 },
      imza: "Herkes Haaland derken Norveç'in kilit adamının kalecisi olacağını tek başına bildi — Brezilya'yı eleyen kurtarışı önceden gördü."
    },
    {
      kisi: "Turancan",
      unvan: "Cesur Ağaç Ustası",
      grupPuan: "10", grupSira: 3,
      sampiyon: { pick: "İngiltere → Arjantin", durum: "ÇÖKTÜ",
        not: "10 Haziran'da İngiltere dedi; 28 Haziran'da Arjantin'e geçti; 8 Temmuz'da 'Arjantin finale çıkarsa %100 şampiyon' diye perçinledi. Arjantin finale çıktı ama kupayı İspanya kaldırdı (19 Tem, 1-0) — '%100' çağrısı son basamakta çöktü. Yüzleşmesi zarifti: kaybedince tebrik gerekir dedi, başının öne eğildiğini saklamadı." },
      tally: { tuttu: 2, kismen: 1, coktu: 7 },
      imza: "K Grubu'nun tüm sıralamasını tam bildi; ama Türkiye'ye '9 puanla lider' dedi."
    },
    {
      kisi: "Hasan",
      unvan: "Yüksek Riskli Oyuncu",
      grupPuan: "12", grupSira: 2,
      sampiyon: { pick: "Portekiz", durum: "ÇÖKTÜ",
        not: "6 Temmuz'da İspanya-Portekiz (1-0, 90+1 Merino) ile şampiyon tahmini turnuvadan elendi. 15 Temmuz'da yeminle Arjantin'e döndü ('totem değil') — o da finalde çöktü. Final gününe İspanya formasıyla girmişti; yeminiyle yayında hiç yüzleşilmedi." },
      tally: { tuttu: 0, kismen: 2, coktu: 8 },
      imza: "Senegal'e yarı final, ABD'ye çeyrek final, Meksika'ya İngiltere galibiyeti yazdı — üçü de gitti."
    }
  ],

  sampiyonEvrimi: [
    { t: "10 Haz", olay: "Turnuva ağaçları çizildi: Hasan → Portekiz, Turancan → İngiltere, Hilmi → İspanya.", video: "usNy-VEb-wQ" },
    { t: "28 Haz", olay: "Son 32 ağacında iki isim şampiyonunu değiştirdi: Turancan → Arjantin (finalde Fransa'yı yener), Hilmi → Arjantin.", video: "mEi2Is3ekE0" },
    { t: "6 Tem", olay: "Portekiz elendi (İspanya 1-0, 90+1 Merino) — Hasan'ın şampiyonu turnuvadan düştü, Ronaldo gözyaşlarını tuttu.", video: "wX1PGT1zHto" },
    { t: "8 Tem", olay: "Turancan: 'Arjantin finale çıkarsa yüzde yüz şampiyon.' Hilmi ise Arjantin'in 19 Temmuz'a kadar tükeneceğinden şüpheli.", video: "_vs_fz92o4M" },
    { t: "11 Tem", olay: "Yarı final belli oldu: FRANSA-İSPANYA. Yani Hasan'ın 'Fransa şampiyonsa Dembele Ballon d'Or' koşulunun takımı, Hilmi'nin 10 Haziran'da seçip 28 Haziran'da terk ettiği İspanya'yla karşı karşıya. Bu gece: Norveç-İngiltere — Turancan'ın ilk şampiyonu ve 'kimse inanmamıştı' çağrısı aynı sahnede.", video: "SRqMJv8FtBI" },
    { t: "11 Tem", olay: "Norveç 1-2 İngiltere (kazandıran gol Bellingham'dan, 90+3'te). Turancan'ın 'kimse inanmadı' Norveç çağrısı yarı finalin bir adım önünde bitti — ama İngiltere yarı finalde, yani Turancan'ın 10 Haziran'daki İLK şampiyonu hâlâ yarışta. Yarı finaller: Fransa-İspanya ve İngiltere-(Arjantin/İsviçre).", video: null },
    { t: "14 Tem", olay: "Fransa 0-2 İspanya (22' Oyarzabal penaltı, 58' Pedro Porro) — Hasan'ın Dembele/Fransa şampiyonluk koşulu çöktü; Hilmi'nin 10 Haziran'da seçip 28 Haziran'da TERK ETTİĞİ İspanya finale yükseldi. Diğer yarı final İngiltere-Arjantin bugün (15 Tem) oynanıyor — Turancan'ın iki şampiyon adayı da bu maçta karşı karşıya, final rakibi belirlenecek.", video: "PkkYh9lL4_c" },
    { t: "15 Tem", olay: "Arjantin 2-1 İngiltere (55' Gordon İngiltere; 85' Enzo Fernández, 90+2' Lautaro Martínez — Arjantin'den geriden gelen final): Turancan'ın ilk şampiyonu (İngiltere) elendi, ama 28 Haziran'dan beri sarıldığı Arjantin finale çıktı — 'Arjantin finale çıkarsa yüzde yüz şampiyon' çağrısının ilk yarısı doğrulandı. Final tablosu netleşti: İSPANYA-ARJANTİN, 19 Temmuz. Hilmi'nin hem 10 Haziran'daki İLK seçimi (İspanya) hem 28 Haziran'dan beri sarıldığı Arjantin finalde — hangisi kazanırsa kazansın bir tahmini haklı çıkacak.", video: "EcRrNB8ex7c" },
    { t: "15-16 Tem", olay: "Final cepheleri netleşti. Hilmi üçüncü dönüşünü yaptı: maç önü yayınında finale İspanya formasıyla döneceğini açıkladı — 10 Haziran'da başladığı yere. Hasan ise turnuva boyu durduğu Arjantin karşıtı cepheden yeminle ayrıldı: 'Totem değil — Arjantin finali kazanır, hatta final Messi'nin turnuvadaki en kolay maçı olur.' Skor tablosu: Hasan+Turancan → Arjantin, Hilmi → İspanya. 19 Temmuz'da en az biri kesin yanılacak.", video: "EcRrNB8ex7c" },
    { t: "19 Tem", olay: "FİNAL: İspanya 1-0 Arjantin (106' Ferran Torres; 90+'da Enzo Fernández ikinci sarıdan atıldı). Hilmi'nin 10 Haziran'da başlayıp 15 Temmuz'da geri döndüğü İspanya kupayı kaldırdı — üç dönüşün sonunda hem başladığı hem bitirdiği tahmin şampiyon. Turancan'ın '%100 şampiyon' çağrısı ve Hasan'ın yeminli Arjantin dönüşü aynı gece çöktü. Turnuvanın en iyisi Rodri seçildi; Mbappé gol krallığını üçüncülük maçındaki 2 golle Messi'den aldı (10-8). Messi kupasız veda etti — resmî emeklilik açıklaması henüz yok. SİCİL KAPANDI.", video: "i0HDcoR455k" }
  ],

  kayitlar: [
    // ---- ÇÖZÜLMÜŞLER ----
    { kisi: "Hasan", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Turnuva ağacında şampiyon olarak Portekiz'i gösterdi.",
      cozum: "Portekiz son 16'da İspanya'ya 1-0 elendi (90+1 Merino).",
      video: "usNy-VEb-wQ", kanit: "wX1PGT1zHto" },
    { kisi: "Hasan", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Turnuvanın sürprizi Senegal olacak dedi: grupta Fransa'yı geçip Hollanda ve Almanya'yı eleyerek yarı finale kadar gidecekti.",
      cozum: "Fransa grubu lider bitirdi; Senegal 2-0 öne geçtiği maçta 2-2'ye gelinip Belçika'ya elendi.",
      video: "usNy-VEb-wQ", kanit: "QEHMTCbQqnE" },
    { kisi: "Hasan", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Kendi ağacında ev sahibi ABD'yi Bosna ve Belçika'yı geçip çeyrek finale taşıdı (orada İspanya'ya kaybedecekti).",
      cozum: "Belçika, ABD'yi eledi (Lukaku golü, kırmızı kartlı maç).",
      video: "usNy-VEb-wQ", kanit: "7jgCcB60ONA" },
    { kisi: "Hilmi", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Türkiye'nin son 32 turunda Mısır'la eşleşeceğini öngördü.",
      cozum: "Türkiye ilk iki maçını golsüz kaybetti; son maçta ABD'yi 3-2 yenmesine rağmen 3 puanla grup aşamasında elendi.",
      video: "usNy-VEb-wQ", kanit: "U3i9qYWwzoE" },
    { kisi: "Hilmi", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Portekiz'in kolay bir yoldan yarı finale çıkıp orada İngiltere'ye kaybedeceğini öngördü (Ronaldo'nun ağladığı sahneyle).",
      cozum: "Portekiz yarı finali göremeden son 16'da İspanya'ya elendi — ama Ronaldo'nun gözyaşı sahnesi aynen yaşandı.",
      video: "usNy-VEb-wQ", kanit: "wX1PGT1zHto" },
    { kisi: "Turancan", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Portekiz'in (Ronaldo'nun) daha son 32 turunda eleneceğini öngördü.",
      cozum: "Portekiz son 32'de Hırvatistan'ı 2-1 geçti; bir tur sonra elendi.",
      video: "usNy-VEb-wQ", kanit: "2N2NB_blEZo" },
    { kisi: "Turancan", t: "10 Haz", kat: "turnuva", durum: "KISMEN",
      ozet: "Brezilya'nın İsveç karşısında ağır bir yenilgiyle sürpriz şekilde eleneceğini öngördü.",
      cozum: "Sürpriz eleme gerçekleşti ama çeyrek finalde ve Norveç'e karşı — Neymar maç sonrası milli takımı bıraktı. İsveç ise Fransa'ya 3-0 elendi.",
      video: "usNy-VEb-wQ", kanit: "e6xPTfo4qCA" },
    { kisi: "Turancan", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Türkiye'nin çeyrek finale kadar çıkacağını işaretledi; grup aşamasını da 9 puanla lider bitirecekti (13 Haziran'da tekrar etti).",
      cozum: "Türkiye Avustralya'ya 2-0, Paraguay'a 1-0 kaybetti; son maçtaki 3-2'lik ABD galibiyeti yetmedi, grubu 3 puanla son sırada bitirip elendi.",
      video: "usNy-VEb-wQ", kanit: "U3i9qYWwzoE" },
    { kisi: "Hasan", t: "14 Haz", kat: "turnuva", durum: "KISMEN",
      ozet: "Avustralya yenilgisi sonrası: 'Paraguay'ı tartışmasız yeneriz, ABD'ye de yenilmeyiz' dedi.",
      cozum: "Paraguay'a 1-0 yenildi (çöktü); son maçta ABD 3-2 yenildi (tuttu).",
      video: "bO4XZAbdmQ8", kanit: "Q3veOupQsVk" },
    { kisi: "Turancan", t: "22 Haz", kat: "turnuva", durum: "TUTTU",
      ozet: "Norveç'in H Grubu'nu (Uruguay'ın önünde) lider bitireceğini savundu — turnuva öncesi ağaçlarda bunu kimse yazmamıştı.",
      cozum: "Norveç grubu lider bitirdi; sonra Fildişi'ni ve BREZİLYA'yı eledi. Yolculuk çeyrek finalde İngiltere'ye 90+3'te gelen golle 1-2 bitti — yarı finalin bir adım önünde. Turnuva öncesi kimse yazmazken buraya kadar gelmesi çağrıyı fazlasıyla haklı çıkardı.",
      video: "-OC5KTxz7Ig", kanit: "KVik2_JlLko" },
    { kisi: "Hilmi", t: "18 Haz", kat: "skor", durum: "KISMEN",
      ozet: "İsviçre'nin Bosna Hersek'i tek farkla yeneceğini tahmin etti.",
      cozum: "İsviçre kazandı ama fark 1 gol değildi.",
      video: "HSPOt6RsDPg", kanit: "HSPOt6RsDPg" },
    { kisi: "Hilmi", t: "18 Haz", kat: "oyuncu", durum: "COKTU",
      ozet: "Genç Manzambi'yi tek maçına bakıp 'çöp' ilan etmişti.",
      cozum: "Manzambi yedekten girip 2 gol attı ve 20 yaş 247 günle Dünya Kupası tarihinde bunu başaran en genç oyuncu oldu.",
      video: "HSPOt6RsDPg", kanit: "HSPOt6RsDPg" },
    { kisi: "Hilmi", t: "5 Tem", kat: "oyuncu", durum: "TUTTU",
      ozet: "Brezilya-Norveç öncesi herkes Haaland derken ısrarla 'Norveç'in kilit adamı kaleci olacak' dedi.",
      cozum: "Norveç 1-0 öndeyken kalecisi maçı çeviren kritik kurtarışı yaptı; Brezilya çeyrek finalde elendi.",
      video: "e6xPTfo4qCA", kanit: "e6xPTfo4qCA" },
    { kisi: "Hasan", t: "30 Haz", kat: "skor", durum: "KISMEN",
      ozet: "Meksika-Ekvador'un 90 dakikada berabere bitip uzatmada Meksika'nın kazanacağını söyledi.",
      cozum: "Kazananı bildi — Meksika turu geçip son 16'da İngiltere'yle eşleşti; uzatma senaryosu transkriptlerden doğrulanamadı.",
      video: "-e904IkD6uw", kanit: "8fckW0xyH7k" },
    // ---- KANALIN KENDİ PUANLAMASI (28 Haz yüzleşme yayını) ----
    { kisi: "Hilmi", t: "28 Haz", kat: "grup karnesi", durum: "TUTTU",
      ozet: "12 grubun toplamında en yüksek puanı toplayarak grup tahminlerinin açık ara birincisi oldu (E Grubu'nu neredeyse tam bildi).",
      cozum: "Kanalın kendi puanlaması: Hilmi 28+ puan, Hasan 12, Turancan 10.",
      video: "KVik2_JlLko", kanit: "KVik2_JlLko" },
    { kisi: "Turancan", t: "28 Haz", kat: "grup karnesi", durum: "TUTTU",
      ozet: "K Grubu'nun tüm sıralamasını tam bildi; C Grubu'nda 3.-4. sırayı bilerek gruba yakın tam puan aldı; G Grubu'nda Yeşil Burun'un ikinciliğini tek bilen oldu.",
      cozum: "Kanalın kendi puanlamasıyla üç grupta zirve; ama genel toplamda 10 puanla sonuncu.",
      video: "KVik2_JlLko", kanit: "KVik2_JlLko" },
    { kisi: "Turancan", t: "28 Haz", kat: "grup karnesi", durum: "COKTU",
      ozet: "D Grubu'nda Türkiye'yi lider yazmıştı — kendisi de bunun yarı manifest olduğunu itiraf etti.",
      cozum: "ABD grubu lider bitirdi; D grubu puanlamasında Hilmi 2, Hasan ve Turancan 0 aldı.",
      video: "KVik2_JlLko", kanit: "KVik2_JlLko" },
    { kisi: "Hasan", t: "28 Haz", kat: "grup karnesi", durum: "COKTU",
      ozet: "J Grubu'nda Özbek oyunculara (Şomurodov, Fayzullaev...) duyduğu güvenle iddialı bir sıralama yazmıştı.",
      cozum: "Grup 'üzücü' bitti; Özbekistan güveni Hasan'a puan kaybettirdi — yayında espri konusu oldu.",
      video: "KVik2_JlLko", kanit: "KVik2_JlLko" },
    // ---- BEKLEYENLER ----
    { kisi: "Hasan", t: "5 Tem", kat: "turnuva", durum: "COKTU",
      ozet: "Meksika'nın İngiltere'yi 90 dakikada yenip turnuvada tarih yazacağını söyledi.",
      cozum: "İngiltere turu geçti ve çeyrek finalde Norveç'i 2-1 yendi; Meksika turnuva dışı.",
      video: "H9wsL6yVgyM", kanit: "3Vl3PNsRqQ8" },
    { kisi: "Turancan", t: "8 Tem", kat: "turnuva", durum: "COKTU",
      ozet: "'Arjantin finale çıkarsa, rakip Fransa bile olsa yüzde yüz şampiyon' dedi.",
      cozum: "Arjantin finale çıktı — ama İspanya finalde 1-0 kazandı (106' Ferran Torres, uzatma). '%100' iddiası son basamakta çöktü. Maç sonu yayınındaki yüzleşmesi zarifti: kaybedince tebrik gerekir dedi.",
      video: "_vs_fz92o4M", kanit: "i0HDcoR455k" },
    { kisi: "Turancan", t: "13 Haz", kat: "oyuncu", durum: "COKTU",
      ozet: "'Niş tahmin': Türkiye'nin Dünya Kupası'ndaki ilk golünü Zeki Çelik atacaktı.",
      cozum: "Türkiye'nin turnuvadaki ilk golü Arda Güler'den geldi (10. dakika, Türkiye-ABD 3-2, 25 Haz). Zeki Çelik turnuvayı golsüz kapadı.",
      video: "ssRo1VjOSMU", kanit: null },
    { kisi: "Turancan", t: "17 Haz", kat: "oyuncu", durum: "COKTU",
      ozet: "İngiltere 60 yıl sonra kupayı kazanırsa Ballon d'Or'un Harry Kane'e gideceğini söyledi.",
      cozum: "İngiltere yarı finalde Arjantin'e 1-2 kaybedip elendi (15 Tem) — koşul hiç gerçekleşmeyecek.",
      video: "sVR8mv4AIPc", kanit: "EcRrNB8ex7c" },
    { kisi: "Hasan", t: "26 Haz", kat: "oyuncu", durum: "COKTU",
      ozet: "Fransa şampiyon olursa Dembele'nin (turnuvada 4 gol) Ballon d'Or'u garantileyeceğini söyledi.",
      cozum: "Fransa yarı finalde İspanya'ya 0-2 kaybetti (14 Tem, Dallas — 22' Oyarzabal penaltı, 58' Pedro Porro) — şampiyonluk ihtimali bitti, koşul hiç gerçekleşmeyecek.",
      video: "HCfRvcR8RxI", kanit: "PkkYh9lL4_c" },
    { kisi: "Hilmi", t: "11 Tem", kat: "sampiyon", durum: "KISMEN",
      ozet: "Kalan 5 takım için şampiyonluk yüzdesi verdi: Fransa %40 (açık favori), Arjantin %20, İspanya %20, İngiltere %18, İsviçre en düşük.",
      cozum: "En yüksek yüzdeyi verdiği Fransa yarı finalde elendi — favorisi yanlıştı. Ama şampiyon İspanya, listesinde %20 ile İngiltere'nin önündeydi ve finalin iki takımı da (%20+%20) onun kâğıdındaydı. Yarı isabet.",
      video: "uFBXQy-aENs", kanit: "i0HDcoR455k" },
    { kisi: "Hasan", t: "15 Tem", kat: "skor", durum: "COKTU",
      ozet: "Yarı final sabahı kendine güvenle uyandı: İngiltere kazanacak — hatta 3-0 gibi bir fark olursa İngiltere forması alma sözü verdi.",
      cozum: "Arjantin 2-1 geriden gelerek kazandı. Maç sonu öfke tamamen Tuchel'e döndü: 'üç koyunu emanet etmem' seviyesinde bir teknik-intihar tiradı.",
      video: "PjdoI0H8K7M", kanit: "EcRrNB8ex7c" },
    { kisi: "Hilmi", t: "15 Tem", kat: "kupon", durum: "COKTU",
      ozet: "Günün kupondaş kuponunu kurdu (Turancan 'sen ne dersen tamam' diye ortak oldu): Kane gol atar + İngiltere kazanır, 3.68 oran.",
      cozum: "Kane maç boyu Arjantin ceza sahasında topla neredeyse hiç buluşamadı, İngiltere 2-1 kaybetti — kupon yattı. Bir önceki günün kuponu da yatmıştı.",
      video: "PjdoI0H8K7M", kanit: "EcRrNB8ex7c" },
    { kisi: "Hasan", t: "15 Tem", kat: "sampiyon", durum: "COKTU",
      ozet: "Turnuva boyu Arjantin karşıtı cephenin lideriyken maç sonu yayınında yeminle döndü: 'Totem değil — Arjantin finali kazanır; hatta final, Messi'nin turnuvadaki en kolay maçı olur.'",
      cozum: "İspanya finali 1-0 kazandı ve Arjantin'e ilk yarıyı 60 yıl sonra şutsuz kapattırdı — 'en kolay maç' bir yana, Messi'nin en çaresiz gecesiydi. Yemin, final gecesi yayınlarında bir kez bile anılmadı; Hasan final gününe İspanya formasıyla girmişti.",
      video: "EcRrNB8ex7c", kanit: "i0HDcoR455k" },
    { kisi: "Hilmi", t: "15 Tem", kat: "sampiyon", durum: "TUTTU",
      ozet: "Final tahmini: rahat bir İspanya galibiyeti — 'Fransa'ya karşı alınan 2-0 gibi, rakibe şans tanımayan kontrollü bir üstünlük.' Sözünü formayla mühürledi: finale İspanya formasıyla çıktı.",
      cozum: "İspanya şampiyon — skor 1-0 (uzatma) olsa da kanalın kendi hükmü netti: 'Skora aldanmayın, beş kere oynansa beşinde üçten fazla atardı; ezdi.' Hilmi kanalın tahmin oyununu da son turda İspanya'yı bilerek ikinci kez şampiyon bitirdi.",
      video: "EcRrNB8ex7c", kanit: "i0HDcoR455k" },
    { kisi: "Turancan", t: "15 Tem", kat: "oyuncu", durum: "BEKLIYOR",
      ozet: "'Bu, Messi'nin veda turnuvası' iddiasını %100'e çıkardı: finali kazansa da kaybetse de kramponları asacak.",
      cozum: "Güçlü sinyaller var — Messi finale kramponunda 'Son Dans' yazısıyla çıktı, final öncesi 'The Last Tango' paylaşımı yaptı — ama resmî açıklama hâlâ yok. Kanal konsensüsü: 'zirvede bıraktı.' Sicilin kapanmayan tek kaydı bu.",
      video: "EcRrNB8ex7c", kanit: "i0HDcoR455k" },
    { kisi: "Turancan", t: "15 Tem", kat: "senaryo", durum: "COKTU",
      ozet: "Kanal rekorunu kırdıracak final senaryosunu maç önünden yazdı: İspanya 2-0 öne geçecek, Arjantin uzatmanın 120. dakikasında Messi'nin golüyle 3-2 kazanacak.",
      cozum: "Uzatma kısmını bildi — ama tek golü İspanya attı (106' Ferran Torres) ve Messi'nin gecesi golsüz bitti. Senaryonun tam tersi: uzatmada yıkılan taraf Arjantin oldu.",
      video: "PjdoI0H8K7M", kanit: "i0HDcoR455k" },
    { kisi: "Hilmi", t: "19 Tem", kat: "skor", durum: "KISMEN",
      ozet: "Final günü son skor tahmini: İspanya 3-0 — 'şaşırmayacağım tek senaryo bu.' Gol sıralaması bile hazırdı: önce sürpriz bir isim (Cubarsí ya da Laporte), sonra Yamal, sonra Merino.",
      cozum: "Galibi ve maçın karakterini bildi, skoru bilemedi: İspanya ezdi ama gol uzatmada tek geldi (1-0). Golcü listesi de tutmadı — Ferran Torres'i kimse yazmamıştı.",
      video: "4tab2BjgZ4o", kanit: "i0HDcoR455k" }
  ],

  yuzlesmeKosesi: [
    { t: "11 Tem", olay: "Sadakat testi: Norveç elenirken bile Turancan takımını reddetmedi — hakem tartışmasında 'ufak takımı kollayın' deyip 'Norveç müthiş oynadı' diye övgüsünü sürdürdü. Kimse 'öve öve bitirmiştin' diye takılmadı; o kendi çağrısının arkasında durdu.", video: "uFBXQy-aENs" },
    { t: "13 Haz", olay: "Katar'a önceki yayında verilen 'sıfır' notu izleyici tarafından hatırlatıldı; ekip 'ilk patlamamız' diye kabul etti (Katar 1-1 İsviçre).", video: "ssRo1VjOSMU" },
    { t: "28 Haz", olay: "D Grubu tahminleri yayında unutuldu; izleyiciler uyarınca sonradan eklendi — Hilmi 2 puan aldı, diğerleri 0.", video: "KVik2_JlLko" },
    { t: "19 Tem", olay: "Revizyonizm alarmı: Hilmi maç sonu yayınında 'turnuva başından beri favorim İspanya'ydı, hiç dönmedim' diye zafer turu attı. Sicil hatırlıyor: 28 Haziran'da şampiyon kâğıdını Arjantin'e yazdı, 15 Temmuz'da İspanya'ya geri döndü. Sonuç doğru — hikâye eksik.", video: "i0HDcoR455k" },
    { t: "19 Tem", olay: "Sessiz geçiş: Hasan'ın 15 Temmuz'daki yeminli 'Arjantin kazanır' tahmini final gecesi iki yayında da bir kez bile anılmadı; 'maç başında üçümüz de İspanya demiştik herhalde' cümlesi düzeltilmeden geçti. Sicil sessiz geçmiyor.", video: "i0HDcoR455k" }
  ],

  dun: {
    baslik: "SİCİL KAPANDI: İspanya dünya şampiyonu — kâhin belli",
    ozet: "Final: İspanya 1-0 Arjantin (uzatmada 106' Ferran Torres). Hilmi'nin 10 Haziran'da başlayıp üç dönüşün sonunda geri geldiği İspanya kupayı kaldırdı; kanalın kendi tahmin oyununu da ikinci kez şampiyon bitirdi. Turancan'ın '%100 şampiyon' çağrısı son basamakta çöktü — yüzleşmesi zarifti. Hasan'ın yeminli Arjantin dönüşü de çöktü — yemin final gecesi hiç anılmadı; sicil not düştü. Tatlı detaylar: turnuvanın en iyisi Rodri seçildi (15 Temmuz'da şaka yollu 'Rodri'ye verilsin' denmişti); Mbappé gol krallığını son maçta Messi'den aldı — Hasan'ın 15 Temmuz'daki korkusu aynen gerçekleşti. Kanal kupayı 63 yayın, 30M+ görüntülenme ve canlı yayında dolan 755.000 aboneyle kapattı. 4 Haziran'dan 19 Temmuz'a her tahmin, her dönüş, her yüzleşme bu sayfada."
  },

  ironi: "Hilmi 28 Haziran'da şampiyonluk kâğıdını İspanya'dan çekip Arjantin'e yazdı; 15 Temmuz'da pişman olup geri döndü. İspanya kupayı kaldırdı. Üç dönüşün sonunda turnuvanın en kararsız adamı, en haklı adam çıktı — maç sonu yayınında 'hiç dönmedim' diye zafer turu atarken bile. Dönüşünü sicil hatırlıyor; ama tahmin oyununu da ikinci kez şampiyon bitirdiği için kimsenin itiraz edecek yüzü yoktu.",

  oduller: [
    { buyuk: true, tint: "maks", damga: "Maksimüs", rozet: "🏆 Kâhin Anı", kisi: "HİLMİ",
      baslik: "Herkes Haaland derken", vurguBaslik: "tek başına kaleciyi işaret etti",
      metin: "Brezilya-Norveç öncesi bütün gözler Haaland'daydı. Hilmi ısrarla \"Norveç'in kilit adamı kaleci olacak\" dedi. Sonuç: Norveç 1-0 öndeyken kalecisi maçı çeviren kritik kurtarışı yaptı, favori <b>Brezilya çeyrek finalde elendi</b>.",
      kanitEtiket: "5 Temmuz yayını", kanitVideo: "e6xPTfo4qCA", emoji: "🔮" },
    { tint: "cop", damga: "Çöp", rozet: "🗑️ En Büyük Sıçış", kisi: "HİLMİ",
      baslik: "Bir çocuğu tek maçta", vurguBaslik: "\"çöp\" ilan etti",
      metin: "Aynı kâhin, genç Manzambi'yi tek maçına bakıp gözden çıkardı. Aynı yayında yüzleşme geldi: çocuk yedekten girip <b>2 gol attı</b> ve 20 yaş 247 günle Dünya Kupası tarihinde bunu başaran en genç oyuncu oldu.",
      kanitEtiket: "18 Haziran yayını", kanitVideo: "HSPOt6RsDPg", emoji: "🗑️" },
    { tint: "maks", rozet: "⚡ En Cesur Çağrı", kisi: "TURANCAN",
      baslik: "Kimse yazmazken", vurguBaslik: "Norveç dedi",
      metin: "Turnuva öncesi ağaçlarda Norveç'i grup lideri gösteren tek isim oydu. Norveç grubu lider bitirdi, Fildişi'ni ve <b>Brezilya'yı eledi</b>; yolculuk çeyrek finalde İngiltere'ye 90+3'te gelen golle 1-2 bitti — yarı finalin bir adım önünde.",
      kanitEtiket: "22 Haziran yayını", kanitVideo: "-OC5KTxz7Ig" },
    { tint: "cop", rozet: "💔 En Hızlı Çöküş", kisi: "HASAN",
      baslik: "Şampiyonu son 16'da,", vurguBaslik: "Meksika hayali son 16'da gitti",
      metin: "Şampiyon seçtiği Portekiz son 16'da İspanya'ya 90+1'de elendi. \"Meksika İngiltere'yi yener, tarih yazar\" dedi — İngiltere yarı finalde. \"Fransa şampiyon olursa Dembele Ballon d'Or alır\" dedi — Fransa yarı finalde İspanya'ya elendi. Çözülen tahminlerinde <b>0 tuttu, 6 çöktü</b>.",
      kanitEtiket: "6 Temmuz yayını", kanitVideo: "wX1PGT1zHto" },
    { tint: "maks", rozet: "🛡️ Sadakat Ödülü", kisi: "TURANCAN",
      baslik: "Takımı elenirken bile", vurguBaslik: "arkasını dönmedi",
      metin: "Norveç çeyrek finalde giderken kimse \"öve öve bitirmiştin\" diye takılmadı — ama Turancan zaten geri adım atmadı. Hakem tartışmasında \"ufak takımı kollayın\" deyip <b>\"Norveç müthiş oynadı\"</b> diye çağrısının arkasında durdu.",
      kanitEtiket: "11 Temmuz yayını", kanitVideo: "uFBXQy-aENs" },
    { tint: "maks", rozet: "🎯 En İyi Karne", kisi: "HİLMİ",
      baslik: "Grup tahminlerinde", vurguBaslik: "açık ara birinci",
      metin: "Ekibin kendi puanladığı yüzleşme yayınında 12 grubun sıralamasını en iyi bilen Hilmi oldu: <b>28+ puan</b>. Hasan 12'de, Turancan 10'da kaldı — kâhin lakabı burada mühürlendi.",
      kanitEtiket: "28 Haziran yayını", kanitVideo: "KVik2_JlLko" },
    { tint: "notr", rozet: "⏳ Bekleyen Bomba", kisi: "HENÜZ ÇÖZÜLMEDİ",
      baslik: "Mühürlenmiş,", vurguBaslik: "patlaması beklenen iddialar",
      metin: "Turancan: <b>\"Arjantin finale çıkarsa yüzde yüz şampiyon.\"</b> Arjantin, İngiltere'yi 2-1 geçip finale çıktı (15 Tem) — çağrının yarısı doğrulandı, kalan yarısı 19 Temmuz'da. Hilmi'nin durumu daha da çarpıcı: hem ilk seçimi İspanya hem sonradan sarıldığı Arjantin finalde — ne olursa olsun bir tahmini haklı çıkacak.",
      kanitEtiket: "canlı sicilde izle", kanitVideo: null }
  ]
};
