// TAHMİN SİCİLİ — veri seti v1 (9 Temmuz 2026)
// Kaynak: 51 DK-dönemi yayınının transkript çıkarımı (859 tahmin tespit edildi;
// yalnız bağlam kanıtıyla kişiye atananlar yayınlanır). Hükümler, yayınlarda
// söylenen sonuçlara dayanır; her kayıtta kaynak yayın linki vardır.
const SICIL = {
  guncelleme: "15 Temmuz 2026",
  kapsam: { yayin: 51, tahmin: 859, atanmis: 127, yuzlesme: 101 },

  karne: [
    {
      kisi: "Hilmi",
      unvan: "Kanalın Kâhini",
      grupPuan: "28+", grupSira: 1,
      sampiyon: { pick: "İspanya → Arjantin", durum: "KARARSIZ",
        not: "10 Haziran'da İspanya dedi, 28 Haziran'da Arjantin'e döndü, 8 Temmuz'da Arjantin'den de şüpheye düştü. Terk ettiği İspanya ise Belçika'yı ve Fransa'yı da eleyip FİNALE çıktı — kupaya tek maç uzakta." },
      tally: { tuttu: 2, kismen: 1, coktu: 3 },
      imza: "Herkes Haaland derken Norveç'in kilit adamının kalecisi olacağını tek başına bildi — Brezilya'yı eleyen kurtarışı önceden gördü."
    },
    {
      kisi: "Turancan",
      unvan: "Cesur Ağaç Ustası",
      grupPuan: "10", grupSira: 3,
      sampiyon: { pick: "İngiltere → Arjantin", durum: "YAŞIYOR",
        not: "10 Haziran'da İngiltere (final: İspanya-İngiltere) dedi; 28 Haziran'da Arjantin'e geçti; 8 Temmuz'da 'Arjantin finale çıkarsa %100 şampiyon' diye perçinledi. İkisi de hâlâ kupada." },
      tally: { tuttu: 2, kismen: 1, coktu: 3 },
      imza: "K Grubu'nun tüm sıralamasını tam bildi; ama Türkiye'ye '9 puanla lider' dedi."
    },
    {
      kisi: "Hasan",
      unvan: "Yüksek Riskli Oyuncu",
      grupPuan: "12", grupSira: 2,
      sampiyon: { pick: "Portekiz", durum: "ÇÖKTÜ",
        not: "6 Temmuz'da İspanya-Portekiz (1-0, 90+1 Merino) ile şampiyon tahmini turnuvadan elendi." },
      tally: { tuttu: 0, kismen: 2, coktu: 6 },
      imza: "Senegal'e yarı final, ABD'ye çeyrek final, Meksika'ya İngiltere galibiyeti yazdı — üçü de gitti."
    }
  ],

  sampiyonEvrimi: [
    { t: "10 Haz", olay: "Turnuva ağaçları çizildi: Hasan → Portekiz, Turancan → İngiltere, Hilmi → İspanya.", video: "usNy-VEb-wQ" },
    { t: "28 Haz", olay: "Son 32 ağacında iki isim şampiyonunu değiştirdi: Turancan → Arjantin (finalde Fransa'yı yener), Hilmi → Arjantin.", video: "mEi2Is3ekE0" },
    { t: "6 Tem", olay: "Portekiz elendi (İspanya 1-0, 90+1 Merino) — Hasan'ın şampiyonu turnuvadan düştü, Ronaldo gözyaşlarını tuttu.", video: "wX1PGT1zHto" },
    { t: "8 Tem", olay: "Turancan: 'Arjantin finale çıkarsa yüzde yüz şampiyon.' Hilmi ise Arjantin'in 19 Temmuz'a kadar tükeneceğinden şüpheli.", video: "_vs_fz92o4M" },
    { t: "11 Tem", olay: "Yarı final belli oldu: FRANSA-İSPANYA. Yani Hasan'ın 'Fransa şampiyonsa Dembele Ballon d'Or' koşulunun takımı, Hilmi'nin 10 Haziran'da seçip 28 Haziran'da terk ettiği İspanya'yla karşı karşıya. Bu gece: Norveç-İngiltere — Turancan'ın ilk şampiyonu ve 'kimse inanmamıştı' çağrısı aynı sahnede.", video: "SRqMJv8FtBI" },
    { t: "11 Tem", olay: "Norveç 1-2 İngiltere (kazandıran gol Bellingham'dan, 90+3'te). Turancan'ın 'kimse inanmadı' Norveç çağrısı yarı finalin bir adım önünde bitti — ama İngiltere yarı finalde, yani Turancan'ın 10 Haziran'daki İLK şampiyonu hâlâ yarışta. Yarı finaller: Fransa-İspanya ve İngiltere-(Arjantin/İsviçre).", video: null },
    { t: "14 Tem", olay: "Fransa 0-2 İspanya (22' Oyarzabal penaltı, 58' Pedro Porro) — Hasan'ın Dembele/Fransa şampiyonluk koşulu çöktü; Hilmi'nin 10 Haziran'da seçip 28 Haziran'da TERK ETTİĞİ İspanya finale yükseldi. Diğer yarı final İngiltere-Arjantin bugün (15 Tem) oynanıyor — Turancan'ın iki şampiyon adayı da bu maçta karşı karşıya, final rakibi belirlenecek.", video: "PkkYh9lL4_c" }
  ],

  kayitlar: [
    // ---- ÇÖZÜLMÜŞLER ----
    { kisi: "Hasan", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Turnuva ağacında şampiyon olarak Portekiz'i gösterdi.",
      cozum: "Portekiz son 16'da İspanya'ya 1-0 elendi (90+1 Merino).",
      video: "usNy-VEb-wQ", kanit: "wX1PGT1zHto" },
    { kisi: "Hasan", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Turnuvanın sürprizi Senegal olacak dedi: grupta Fransa'yı geçip Hollanda ve Almanya'yı eleyerek yarı finale kadar gidecekti.",
      cozum: "Fransa grubu lider bitirdi; Senegal 2-0 öne geçtiği maçta 2-2'ye gelinip Belçika'ya elendi.",
      video: "usNy-VEb-wQ", kanit: "QEHMTCbQqnE" },
    { kisi: "Hasan", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Kendi ağacında ev sahibi ABD'yi Bosna ve Belçika'yı geçip çeyrek finale taşıdı (orada İspanya'ya kaybedecekti).",
      cozum: "Belçika, ABD'yi eledi (Lukaku golü, kırmızı kartlı maç).",
      video: "usNy-VEb-wQ", kanit: "7jgCcB60ONA" },
    { kisi: "Hilmi", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Türkiye'nin son 32 turunda Mısır'la eşleşeceğini öngördü.",
      cozum: "Türkiye ilk iki maçını golsüz kaybetti; son maçta ABD'yi 3-2 yenmesine rağmen 3 puanla grup aşamasında elendi.",
      video: "usNy-VEb-wQ", kanit: "U3i9qYWwzoE" },
    { kisi: "Hilmi", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Portekiz'in kolay bir yoldan yarı finale çıkıp orada İngiltere'ye kaybedeceğini öngördü (Ronaldo'nun ağladığı sahneyle).",
      cozum: "Portekiz yarı finali göremeden son 16'da İspanya'ya elendi — ama Ronaldo'nun gözyaşı sahnesi aynen yaşandı.",
      video: "usNy-VEb-wQ", kanit: "wX1PGT1zHto" },
    { kisi: "Turancan", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Portekiz'in (Ronaldo'nun) daha son 32 turunda eleneceğini öngördü.",
      cozum: "Portekiz son 32'de Hırvatistan'ı 2-1 geçti; bir tur sonra elendi.",
      video: "usNy-VEb-wQ", kanit: "2N2NB_blEZo" },
    { kisi: "Turancan", t: "10 Haz", kat: "turnuva", durum: "KISMEN",
      ozet: "Brezilya'nın İsveç karşısında ağır bir yenilgiyle sürpriz şekilde eleneceğini öngördü.",
      cozum: "Sürpriz eleme gerçekleşti ama çeyrek finalde ve Norveç'e karşı — Neymar maç sonrası milli takımı bıraktı. İsveç ise Fransa'ya 3-0 elendi.",
      video: "usNy-VEb-wQ", kanit: "e6xPTfo4qCA" },
    { kisi: "Turancan", t: "10 Haz", kat: "turnuva", durum: "COKTU",
      ozet: "Türkiye'nin çeyrek finale kadar çıkacağını işaretledi; grup aşamasını da 9 puanla lider bitirecekti (13 Haziran'da tekrar etti).",
      cozum: "Türkiye Avustralya'ya 2-0, Paraguay'a 1-0 kaybetti; son maçtaki 3-2'lik ABD galibiyeti yetmedi, grubu 3 puanla son sırada bitirip elendi.",
      video: "usNy-VEb-wQ", kanit: "U3i9qYWwzoE" },
    { kisi: "Hasan", t: "14 Haz", kat: "turnuva", durum: "KISMEN",
      ozet: "Avustralya yenilgisi sonrası: 'Paraguay'ı tartışmasız yeneriz, ABD'ye de yenilmeyiz' dedi.",
      cozum: "Paraguay'a 1-0 yenildi (çöktü); son maçta ABD 3-2 yenildi (tuttu).",
      video: "bO4XZAbdmQ8", kanit: "Q3veOupQsVk" },
    { kisi: "Turancan", t: "22 Haz", kat: "turnuva", durum: "TUTTU",
      ozet: "Norveç'in H Grubu'nu (Uruguay'ın önünde) lider bitireceğini savundu — turnuva öncesi ağaçlarda bunu kimse yazmamıştı.",
      cozum: "Norveç grubu lider bitirdi; sonra Fildişi'ni ve BREZİLYA'yı eledi. Yolculuk çeyrek finalde İngiltere'ye 90+3'te gelen golle 1-2 bitti — yarı finalin bir adım önünde. Turnuva öncesi kimse yazmazken buraya kadar gelmesi çağrıyı fazlasıyla haklı çıkardı.",
      video: "-OC5KTxz7Ig", kanit: "KVik2_JlLko" },
    { kisi: "Hilmi", t: "18 Haz", kat: "skor", durum: "KISMEN",
      ozet: "İsviçre'nin Bosna Hersek'i tek farkla yeneceğini tahmin etti.",
      cozum: "İsviçre kazandı ama fark 1 gol değildi.",
      video: "HSPOt6RsDPg", kanit: "HSPOt6RsDPg" },
    { kisi: "Hilmi", t: "18 Haz", kat: "oyuncu", durum: "COKTU",
      ozet: "Genç Manzambi'yi tek maçına bakıp 'çöp' ilan etmişti.",
      cozum: "Manzambi yedekten girip 2 gol attı ve 20 yaş 247 günle Dünya Kupası tarihinde bunu başaran en genç oyuncu oldu.",
      video: "HSPOt6RsDPg", kanit: "HSPOt6RsDPg" },
    { kisi: "Hilmi", t: "5 Tem", kat: "oyuncu", durum: "TUTTU",
      ozet: "Brezilya-Norveç öncesi herkes Haaland derken ısrarla 'Norveç'in kilit adamı kaleci olacak' dedi.",
      cozum: "Norveç 1-0 öndeyken kalecisi maçı çeviren kritik kurtarışı yaptı; Brezilya çeyrek finalde elendi.",
      video: "e6xPTfo4qCA", kanit: "e6xPTfo4qCA" },
    { kisi: "Hasan", t: "30 Haz", kat: "skor", durum: "KISMEN",
      ozet: "Meksika-Ekvador'un 90 dakikada berabere bitip uzatmada Meksika'nın kazanacağını söyledi.",
      cozum: "Kazananı bildi — Meksika turu geçip son 16'da İngiltere'yle eşleşti; uzatma senaryosu transkriptlerden doğrulanamadı.",
      video: "-e904IkD6uw", kanit: "8fckW0xyH7k" },
    // ---- KANALIN KENDİ PUANLAMASI (28 Haz yüzleşme yayını) ----
    { kisi: "Hilmi", t: "28 Haz", kat: "grup karnesi", durum: "TUTTU",
      ozet: "12 grubun toplamında en yüksek puanı toplayarak grup tahminlerinin açık ara birincisi oldu (E Grubu'nu neredeyse tam bildi).",
      cozum: "Kanalın kendi puanlaması: Hilmi 28+ puan, Hasan 12, Turancan 10.",
      video: "KVik2_JlLko", kanit: "KVik2_JlLko" },
    { kisi: "Turancan", t: "28 Haz", kat: "grup karnesi", durum: "TUTTU",
      ozet: "K Grubu'nun tüm sıralamasını tam bildi; C Grubu'nda 3.-4. sırayı bilerek gruba yakın tam puan aldı; G Grubu'nda Yeşil Burun'un ikinciliğini tek bilen oldu.",
      cozum: "Kanalın kendi puanlamasıyla üç grupta zirve; ama genel toplamda 10 puanla sonuncu.",
      video: "KVik2_JlLko", kanit: "KVik2_JlLko" },
    { kisi: "Turancan", t: "28 Haz", kat: "grup karnesi", durum: "COKTU",
      ozet: "D Grubu'nda Türkiye'yi lider yazmıştı — kendisi de bunun yarı manifest olduğunu itiraf etti.",
      cozum: "ABD grubu lider bitirdi; D grubu puanlamasında Hilmi 2, Hasan ve Turancan 0 aldı.",
      video: "KVik2_JlLko", kanit: "KVik2_JlLko" },
    { kisi: "Hasan", t: "28 Haz", kat: "grup karnesi", durum: "COKTU",
      ozet: "J Grubu'nda Özbek oyunculara (Şomurodov, Fayzullaev...) duyduğu güvenle iddialı bir sıralama yazmıştı.",
      cozum: "Grup 'üzücü' bitti; Özbekistan güveni Hasan'a puan kaybettirdi — yayında espri konusu oldu.",
      video: "KVik2_JlLko", kanit: "KVik2_JlLko" },
    // ---- BEKLEYENLER ----
    { kisi: "Hasan", t: "5 Tem", kat: "turnuva", durum: "COKTU",
      ozet: "Meksika'nın İngiltere'yi 90 dakikada yenip turnuvada tarih yazacağını söyledi.",
      cozum: "İngiltere turu geçti ve çeyrek finalde Norveç'i 2-1 yendi; Meksika turnuva dışı.",
      video: "H9wsL6yVgyM", kanit: "3Vl3PNsRqQ8" },
    { kisi: "Turancan", t: "8 Tem", kat: "turnuva", durum: "BEKLIYOR",
      ozet: "'Arjantin finale çıkarsa, rakip Fransa bile olsa yüzde yüz şampiyon' dedi.",
      cozum: "Fransa yarı finalde İspanya'ya elendi (14 Tem, 0-2) — 'rakip Fransa bile olsa' koşulu artık test edilemeyecek, ama esas iddia sürüyor: Arjantin bugün (15 Tem) yarı finalde İngiltere'yle oynuyor, sonuç bekleniyor.",
      video: "_vs_fz92o4M", kanit: "PkkYh9lL4_c" },
    { kisi: "Turancan", t: "13 Haz", kat: "oyuncu", durum: "BEKLIYOR",
      ozet: "'Niş tahmin': Türkiye'nin Dünya Kupası'ndaki ilk golünü Zeki Çelik atacaktı.",
      cozum: "Türkiye'nin ilk golü ABD maçında (3-2) geldi; golcü verisi bir sonraki güncellemede netleşecek.",
      video: "ssRo1VjOSMU", kanit: null },
    { kisi: "Turancan", t: "17 Haz", kat: "oyuncu", durum: "BEKLIYOR",
      ozet: "İngiltere 60 yıl sonra kupayı kazanırsa Ballon d'Or'un Harry Kane'e gideceğini söyledi.",
      cozum: "Koşul canlı: İngiltere hâlâ turnuvada.",
      video: "sVR8mv4AIPc", kanit: null },
    { kisi: "Hasan", t: "26 Haz", kat: "oyuncu", durum: "COKTU",
      ozet: "Fransa şampiyon olursa Dembele'nin (turnuvada 4 gol) Ballon d'Or'u garantileyeceğini söyledi.",
      cozum: "Fransa yarı finalde İspanya'ya 0-2 kaybetti (14 Tem, Dallas — 22' Oyarzabal penaltı, 58' Pedro Porro) — şampiyonluk ihtimali bitti, koşul hiç gerçekleşmeyecek.",
      video: "HCfRvcR8RxI", kanit: "PkkYh9lL4_c" },
    { kisi: "Hilmi", t: "11 Tem", kat: "sampiyon", durum: "BEKLIYOR",
      ozet: "Kalan 5 takım için şampiyonluk yüzdesi verdi: Fransa %40 (açık favori), Arjantin %20, İspanya %20, İngiltere %18, İsviçre en düşük.",
      cozum: "Fransa (en yüksek yüzdesi) yarı finalde İspanya'ya elendi (14 Tem, 0-2) — favorisi ilk turda düştü. İspanya finale yükseldi; rakibi bugünkü (15 Tem) İngiltere-Arjantin yarı finalinin galibi. Final 19 Temmuz'da netleşecek.",
      video: "uFBXQy-aENs", kanit: "PkkYh9lL4_c" }
  ],

  yuzlesmeKosesi: [
    { t: "11 Tem", olay: "Sadakat testi: Norveç elenirken bile Turancan takımını reddetmedi — hakem tartışmasında 'ufak takımı kollayın' deyip 'Norveç müthiş oynadı' diye övgüsünü sürdürdü. Kimse 'öve öve bitirmiştin' diye takılmadı; o kendi çağrısının arkasında durdu.", video: "uFBXQy-aENs" },
    { t: "13 Haz", olay: "Katar'a önceki yayında verilen 'sıfır' notu izleyici tarafından hatırlatıldı; ekip 'ilk patlamamız' diye kabul etti (Katar 1-1 İsviçre).", video: "ssRo1VjOSMU" },
    { t: "28 Haz", olay: "D Grubu tahminleri yayında unutuldu; izleyiciler uyarınca sonradan eklendi — Hilmi 2 puan aldı, diğerleri 0.", video: "KVik2_JlLko" }
  ],

  dun: {
    baslik: "Bu hafta çözülenler",
    ozet: "Fransa 0-2 İspanya (14 Tem, yarı final): Hasan'ın Dembele/Fransa şampiyonluk koşulu çöktü; Hilmi'nin 10 Haziran'da seçip sonra terk ettiği İspanya finale yükseldi — kupaya tek maç uzakta. Diğer yarı final İngiltere-Arjantin bugün (15 Tem) oynanıyor: Turancan'ın 10 Haziran'daki ilk şampiyonu (İngiltere) ve 28 Haziran'dan beri sarıldığı ikinci şampiyonu (Arjantin) aynı sahada — hangisi kazanırsa Turancan'ın çağrısı finale taşınmış olacak. Final 19 Temmuz."
  }
};
